"""empty message

Revision ID: 2e9a0a0e8090
Revises: a5e65453444a
Create Date: 2021-06-16 23:20:27.190555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9a0a0e8090'
down_revision = 'a5e65453444a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diggers', sa.Column('gold_mine_id', sa.Integer(), nullable=True))
    op.drop_constraint('diggers_car_wash_id_fkey', 'diggers', type_='foreignkey')
    op.create_foreign_key(None, 'diggers', 'goldmines', ['gold_mine_id'], ['id'])
    op.drop_column('diggers', 'car_wash_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diggers', sa.Column('car_wash_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'diggers', type_='foreignkey')
    op.create_foreign_key('diggers_car_wash_id_fkey', 'diggers', 'goldmines', ['car_wash_id'], ['id'])
    op.drop_column('diggers', 'gold_mine_id')
    # ### end Alembic commands ###
