version: "3.9"

networks:
    goldminenetwork:
        name: goldminenetwork

services:
    minedb:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: minedb
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        networks:
            - goldminenetwork
        volumes:
            - "pgdata:/var/lib/postgresql/data"
            
    nginx:
        image: sassiq/nginxconfigs
        restart: always
        networks:
            - goldminenetwork
        ports:
            - "5000:1337"

    mine:
        environment:
            BOT_TOKEN: "1891373209:AAGTLW9Ryz0rFD--U-r7gfFQd2p2lZjFxb4"
            WEBHOOK_URL: "https://fb1b52d810df.ngrok.io"
        image: sassiq/goldminebot
        restart: always
        networks:
            - goldminenetwork
        depends_on:
            - minedb
volumes:
     pgdata:
